apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: fadildev/my-node-app  # Remplacez par votre nom d'utilisateur Docker Hub
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"  # Optionnel, selon votre environnement