apiVersion: v1
kind: Service
metadata:
  name: my-node-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001  # Port externe pour accéder au service
  selector:
    app: my-node-app