---
- name: Installer Docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Démarrer Docker
  service:
    name: docker
    state: started
    enabled: yes
